version: "3"

volumes:
  postgres_data:
  bundle_volume:

services:
  app:
    container_name: rails_app
    hostname: gamapecas
    build:
      context: .
      dockerfile: ./rails_app/Dockerfile
    volumes:
      - ./rails_app/:/usr/src/app
      - bundle_volume:/usr/local/bundle
    env_file: .env
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: postgres:12.2-alpine
    container_name: postgres
    hostname: postgres
    ports:
      - 5432
    restart: always
    environment:
      username: postgres
      POSTGRES_PASSWORD: "${KEY_POSTGRES}"
    volumes:
      - postgres_data:/var/lib/postgresql/data